### ISSUE TITLE
Core changefeeds can't be consumed by all supported drivers

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11005]
While working with an external author on content around core changefeeds, I realized that our docs don't mention anything around which supported drivers can successfully consume core changeeds and which can't. That author found that Java and Go pgx work but psycopg2 does not, for example. 

We should think about how to document this, perhaps as a known limitation for core changefeeds.

**Comment by jseldess** [comment]
cc @vy-ton and @mwang1026, as this overlaps your areas.

**Comment by bdarnell** [comment]
There are also driver-specific nuances that we should document.
- Java (PGJDBC): Must use `setAutoCommit(false)` and `setFetchSize(1)`. Working example: https://replit.com/@BenCockroach/streaming-test-java#Main.java
- Go (pgx): Just works. Example: https://replit.com/@BenCockroach/streaming-test-go#main.go
- Javascript: Requires the use of pg-cursor in addition to the base pg driver. (I don't have an example yet for this one). 
- Python: psycopg2 doesn't work at all with core changefeeds. Other drivers need investigation. (I think I've tried asyncpg and it worked but didn't keep the code around)

**Comment by danthegoodman1** [comment]
Would love a JS one, trying to get it working right now. Will drop in when I get it working.

**Comment by vy-ton** [comment]
@amruss Do you want to drive this from CDC? @ericharmeling can help with figuring how this fits into our driver examples/docs.

**Comment by amruss** [comment]
Yes I can take it - thanks @vy-ton

**Comment by danthegoodman1** [comment]
For JS (TS), I have the following half-working:
```ts
function handleRows(err: any, rows: any) {
  for (const row of rows) {
    console.log(Buffer.from(row.key).toString(), Buffer.from(row.value).toString())
  }
}

async function readRows (cur: any) {
  cur.read(16, (err: any, rows: any) => {
    if (rows) {
      console.log('handling rows...')
      handleRows(err, rows)
      readRows(cur)
    } else {
      console.log('no rows found...')
      setTimeout(() => {
        readRows(cur)
      }, 1000)
    }
  })
}

async function main() {
  const c = await client.connect()
  const q = new Cursor('EXPERIMENTAL CHANGEFEED FOR foo WITH updated;')
  const cur = c.query(q)
  readRows(cur)
}

main()
```

The reason I say half working is that it is highly dependent on how many rows I read. It seems to only read once. If there aren't enough rows to read as many as I am requesting, then it will wait until there are enough rows. As you can see here, I read 16 rows, and it waited until the 16th was available before spitting out all of the rows.

```
handling rows...
[0] {"after": {"a": 0}, "updated": "1628179449905767566.0000000000"}
[1] {"after": {"a": 1}, "updated": "1628179449905767566.0000000000"}
[2] {"after": {"a": 2}, "updated": "1628179449905767566.0000000000"}
[3] {"after": {"a": 3}, "updated": "1628179449905767566.0000000000"}
[4] {"after": {"a": 4}, "updated": "1628179449905767566.0000000000"}
[5] {"after": {"a": 5}, "updated": "1628179449905767566.0000000000"}
[6] {"after": {"a": 6}, "updated": "1628179449905767566.0000000000"}
[7] {"after": {"a": 7}, "updated": "1628179449905767566.0000000000"}
[8] {"after": {"a": 8}, "updated": "1628179449905767566.0000000000"}
[9] {"after": {"a": 9}, "updated": "1628179449905767566.0000000000"}
[10] {"after": {"a": 10}, "updated": "1628179449905767566.0000000000"}
[11] {"after": {"a": 11}, "updated": "1628179449905767566.0000000000"}
[12] {"after": {"a": 12}, "updated": "1628179449905767566.0000000000"}
[13] {"after": {"a": 13}, "updated": "1628179449905767566.0000000000"}
[14] {"after": {"a": 14}, "updated": "1628179449905767566.0000000000"}
[15] {"after": {"a": 15}, "updated": "1628179463865111735.0000000000"}
no rows found...
no rows found...
no rows found...
no rows found...
no rows found...
no rows found...
no rows found...
no rows found...
no rows found...
```

However, if I set it to say 100 rows, it will never read.

Now here is the interesting part: If I read only 1 row, I immediately get feedback, but subsequent reads don't find anymore rows:

```
handling rows...
[0] {"after": {"a": 0}, "updated": "1628179261202171609.0000000000"}
no rows found...
no rows found...
no rows found...
no rows found...
no rows found...
no rows found...
no rows found...
no rows found...
no rows found...
no rows found...
no rows found...
no rows found...
no rows found...
no rows found...
no rows found...
no rows found...
```

Not finding more rows after reading the first one when using `cur.read(1...` is currently where I am stuck, but maybe I am using the cursor incorrectly.

**Comment by danthegoodman1** [comment]
This is divergent from the expected behavior of cursor such as:

```ts
const cursor = c.query(new Cursor('select * from generate_series(0, 5)'))
  cursor.read(100, (err: any, rows: any) => {
    if (err) {
      throw err
    }
    console.log(rows.length == 6)
    cursor.read(100, (err: any, rows: any) => {
      console.log(rows.length == 0)
    })
  })
```

which returns:
```
true
true
```

As it can read 100 rows that in reality only return 6.

**Comment by bdarnell** [comment]
> As it can read 100 rows that in reality only return 6.

This part is as expected - cursor.read will either read N rows or "until the end", but for a changefeed there is no end (unless there is an error). So you should definitely be passing 1 to cursor.read here. 

After you've gotten one empty result, that Cursor object is finished and you need to create a new Cursor to resume the changefeed. But you shouldn't even be hitting that case at all (are you getting anything in `err`?). The rest of your code looks right to me (with n=1) based on reading the pg-cursor docs but I haven't tried anything myself yet.

**Comment by danthegoodman1** [comment]
I was getting similar output here:

```ts
const cur = await c.query(new Cursor('select * from generate_series(0, 5)'))
  cur.read(1, (err: any, rows: any) => {
    console.log('We got the first row set');
    console.log(rows);

    cur.read(1, (err: any, rows: any) => {
        console.log('This is the next row set');
        console.log(rows);
    });
```

out:
```
We got the first row set
[ { generate_series: '0' } ]
This is the next row set
undefined
```

Let me see if any errors are getting output XD

**Comment by danthegoodman1** [comment]
Here is the error output from my first set of code:

```
err null
handling rows...
[0] {"after": {"a": 0}, "updated": "1628180645728621912.0000000000"}
err error: unknown portal "C_1"
    at Parser.parseErrorMessage (/Users/dangoodman/clusterSpaceCode/testCRDBChangefeed/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/dangoodman/clusterSpaceCode/testCRDBChangefeed/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/dangoodman/clusterSpaceCode/testCRDBChangefeed/node_modules/pg-protocol/src/parser.ts:103:30)
    at TLSSocket.<anonymous> (/Users/dangoodman/clusterSpaceCode/testCRDBChangefeed/node_modules/pg-protocol/src/index.ts:7:48)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 72,
  severity: 'ERROR',
  code: '34000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'conn_executor.go',
  line: '1558',
  routine: 'func2'
}
no rows found... undefined
```

**Comment by danthegoodman1** [comment]
Googling found that others have had issues with `pg-cursor` and CRDB before: https://gitmemory.com/issue/brianc/node-postgres/2546/841796438

**Comment by bdarnell** [comment]
Yes, it looks like I may have been misinformed about pg-cursor working here.

**Comment by danthegoodman1** [comment]
Following that example, the following code worls:

```ts
const q = new Query('EXPERIMENTAL CHANGEFEED FOR foo WITH updated;')
  q.on('row', (row) => {
    console.log(Buffer.from(row.key).toString(), Buffer.from(row.value).toString())
  })
  q.on("error", (error) => console.log("ERROR", error))
  q.on("end", (row) => console.log("RESULT"))
  c.query(q)
```

**Comment by danthegoodman1** [comment]
It properly emits all existing rows, and then waits for new changefeed events and emits them as row events when they appear.

**Comment by danthegoodman1** [comment]
Haven't yet figured out how to gracefully close that connection yet however.

**Comment by danthegoodman1** [comment]
@bdarnell For your go example, how would you stop the `reader` goroutine without killing the whole process, since `rows.Next()` blocks until it gets a row?

**Comment by danthegoodman1** [comment]
> @bdarnell For your go example, how would you stop the `reader` goroutine without killing the whole process, since `rows.Next()` blocks until it gets a row?

If only I waited 5 more minutes before asking... here is the working `Go` modifications for it:

```go
func reader(start time.Time, pool *pgxpool.Pool, ctx context.Context) {
	rows, err := pool.Query(ctx, "EXPERIMENTAL CHANGEFEED FOR streaming_test")
	log.Printf("changefeed Query returned after %v", time.Since(start))
	if err != nil {
		panic(err)
	}
	for rows.Next() {
		values, err := rows.Values()
		if err != nil {
			panic(err)
		}
		log.Printf("%v: read %s", time.Since(start), values)
	}
}

// and

ctxx, cancelFunc := context.WithCancel(context.TODO())
go reader(start, pool, ctxx)
```

Calling `cancelFunc()` kills the goroutine.
