### ISSUE TITLE
Add clock sync to troubleshooting guide

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1690]
From Gitter:

Hi, I am trying to setup cockroachdb cluster using these instructions - https://www.cockroachlabs.com/docs/stable/cluster-setup-troubleshooting.html I stared node1 and then let node2 join. This works fine but when I try to add node3 I am getting a crash

```
 I170708 00:01:58.437337 23 gossip/client.go:131  [n?] started gossip client to 10.160.138.187:26257
F170708 00:01:58.440256 26 server/server.go:162  [n?] fewer than half the known nodes are within the maximum offset of 500ms (0 of 1)
goroutine 26 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x0, 0x1a3dc698, 0x2bf5ac0, 0x10)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:858 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x2bf72a0, 0xc400000004, 0x2485ed9, 0x10, 0xa2, 0xc4206e17a0, 0x54)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:724 +0x591
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7f38ddda8000, 0xc420191bc0, 0x4, 0x2, 0x0, 0x0, 0xc420577cf8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:158 +0x4b3
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7f38ddda8000, 0xc420191bc0, 0x1, 0x4, 0x0, 0x0, 0xc420577cf8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:68 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(0x7f38ddda8000, 0xc420191bc0, 0xc420577cf8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:171 +0x76
github.com/cockroachdb/cockroach/pkg/server.NewServer.func1()
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:162 +0xba
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat(0xc4202afb00, 0xc420308680, 0xc420208500, 0x14, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:415 +0x55a
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).GRPCDial.func1.2.1(0x7f38ddda8000, 0xc42047db60)
        /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:297 +0x6b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201ab1e0, 0xc42041a8c0, 0xc42047daa0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad
```

Would really appreciate if someone can help with getting the cluster set up. I had to do some firewall setting changes to allow communication between node1 and node2.

@mberhault:

This error means that the clocks on the various hosts are more than 500ms apart. We recommend running ntp (or similar) for best results (see https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#clock-synchronization).

**Comment by jseldess** [comment]
Related: https://github.com/cockroachdb/docs/issues/960

**Comment by jseldess** [comment]
See https://github.com/cockroachdb/cockroach/pull/16943/files for new error message.
