### ISSUE TITLE
sql: use of COCKROACH_USE_LEGACY_CONN_HANDLING crashes server

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#2597]
Build Tag:    v2.0-beta.20180305

```
panic while executing 1 statements: SHOW TRACE FOR UPSERT INTO _(_, _, _, _, _, _, _, _, _) VALUES (_, _, _, _, _, _, _, _, _); caused by runtime error: invalid memory address or nil pointer dereference

goroutine 440 [running]:
runtime/debug.Stack(0x367c700, 0xc4256ee300, 0x3)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x367c700, 0xc4256ee300, 0xc4206e6000, 0x234b480, 0xc426709470, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:192 +0xaf
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4208065a0, 0x367c700, 0xc4256ee300)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:178 +0xfb
panic(0x234b480, 0xc426709470)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc42579ae00, 0x367c700, 0xc420b6baa0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:361 +0xa1
panic(0x234b480, 0xc426709470)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql.(*Session).maybeRecover(0xc425721300, 0x245691f, 0x9, 0xc4256e827e, 0x184)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:1445 +0x357
panic(0x21d7280, 0x361fa30)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/util/fsm.(*Machine).CurState(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/fsm/fsm.go:148
github.com/cockroachdb/cockroach/pkg/sql.(*SessionTracing).StartTracing(0xc4257213e0, 0x1, 0x22bae00, 0x7f1a7ee3c401, 0xc425a88200)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:1540 +0x4a
github.com/cockroachdb/cockroach/pkg/sql.(*sessionDataMutator).StartSessionTracing(0xc4257213a8, 0x1, 0xc424d7ec00, 0x6d560d, 0x36937a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:1933 +0x44
github.com/cockroachdb/cockroach/pkg/sql.(*showTraceNode).startExec(0xc42675bda0, 0x367c640, 0xc426b5e580, 0xc425721628, 0xc4257215c0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/show_trace.go:208 +0xee
github.com/cockroachdb/cockroach/pkg/sql.startExec.func2(0x245e93e, 0xe, 0x3673840, 0xc42675bda0, 0xc420b9c928, 0xc424d7ed50)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:456 +0x90
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit.func1(0xc4256c3e80, 0x245e93e, 0xe, 0x3673840, 0xc42675bda0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:90 +0x5f
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc4256c3e80, 0x3673840, 0xc42675bda0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:95 +0x3d5f
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc4256c3e80, 0x36734c0, 0xc426b5c840)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:170 +0x1818
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc4256c3e80, 0x3673c00, 0xc426965c20)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:307 +0x3155
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc4256c3e80, 0x36734c0, 0xc426b5c6e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:170 +0x1818
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc4256c3e80, 0x3673c00, 0xc426965e60)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:307 +0x3155
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc4256c3e80, 0x3673900, 0xc426b66070)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:284 +0x2b8f
github.com/cockroachdb/cockroach/pkg/sql.walkPlan(0x367c640, 0xc426b5e580, 0x3673900, 0xc426b66070, 0x2545dd0, 0x0, 0x0, 0xc4267093b0, 0xc425a881e0, 0x20)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:53 +0x135
github.com/cockroachdb/cockroach/pkg/sql.startExec(0x367c640, 0xc426b5e580, 0xc425721628, 0xc4257215c0, 0x3673900, 0xc426b66070, 0x7f1a7eeded90, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:461 +0xd2
github.com/cockroachdb/cockroach/pkg/sql.startPlan(0x367c640, 0xc426b5e580, 0xc425721628, 0xc4257215c0, 0x3673900, 0xc426b66070, 0x0, 0xc425a881e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:400 +0x61
github.com/cockroachdb/cockroach/pkg/sql.(*planTop).start(0xc425721828, 0x367c640, 0xc426b5e580, 0xc425721628, 0xc4257215c0, 0x2d704546, 0x3)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:389 +0xc0
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execLocal(0xc4205a90e0, 0xc4257215c0, 0x3673900, 0xc426b66070, 0x368ad60, 0xc42579ae00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1992 +0x158
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc4205a90e0, 0x367f6c0, 0xc426c0c840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1519680028af3d78, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:2192 +0x7eb
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc4205a90e0, 0xc425721300, 0x367f6c0, 0xc426c0c840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1519680028af3d78, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1807 +0x86b
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execSingleStatement(0xc4205a90e0, 0xc425721300, 0x367f6c0, 0xc426c0c840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1519680028af3d78, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1277 +0x675
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc4205a90e0, 0xc425721300, 0xc426b5ab40, 0x1, 0x1, 0x0, 0x1, 0xc400000101, 0x0, 0x3681e60, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1112 +0x41f
github.com/cockroachdb/cockroach/pkg/sql.runWithAutoRetry(0xc4205a90e0, 0xc425721300, 0xc426b5ab40, 0x1, 0x1, 0xed2300101, 0x0, 0x0, 0x3ff0000000000000, 0xc4256e4000, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:975 +0x3b8
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execParsed(0xc4205a90e0, 0xc425721300, 0xc426b5ab40, 0x1, 0x1, 0x0, 0x0, 0xc424d834f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:822 +0x144
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc4205a90e0, 0xc425721300, 0xc4256e827e, 0x184, 0x0, 0xc4256e827e, 0x184)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:706 +0x215
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc4205a90e0, 0xc425721300, 0xc4256e827e, 0x184, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:633 +0xd0
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc42579ae00, 0xc42579ae28, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:525 +0x1c9
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc42579ae00, 0x367c700, 0xc420b6baa0, 0xc4202c9580, 0x5400, 0x15000, 0xc4207cfa50, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:441 +0x5fe
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc4207cf8c0, 0x367c640, 0xc42575c2c0, 0x3689840, 0xc4256e2000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:456 +0xbc2
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn-fm(0x367c700, 0xc420b6ba70, 0x3689840, 0xc4256e2000, 0xc42038de90, 0xf)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1285 +0x52
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func17.1(0x3689840, 0xc4256e2000)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1287 +0x194
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4208065a0, 0x367c700, 0xc4256ee300, 0xc42000e398, 0x3689840, 0xc4256e2000, 0xc4256ee330)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:140 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:137 +0x263

root@:26257/aiq> *
* ERROR: [n1] Reported as error db5561c342ac43b3af441920cb4911a5
```

**Comment by andreimatei** [comment]
Any reason why you're using that env var?
Is this issue in the docs repo on purpose?

**Comment by robert-s-lee** [comment]
Use of Env Instruction from Nathan.  Issue being in the Docs repo was fat finger

**Comment by andreimatei** [comment]
Aha, I just confronted Nathan about it. Sounds like y'all were interested in tracing with the old executor code to see if it makes a difference.
As can be seen here, that no longer works because I've made backwards-incompatible changes to the tracing code. I realized that at the time but did it anyway. I'm currently deleting the old code and `COCKROACH_USE_LEGACY_CONN_HANDLING`.

Anyway, I think `COCKROACH_USE_LEGACY_CONN_HANDLING` is not the droid you're looking for; seems unlikely that caused regressions explaining whatever latency you're investigating here.

Btw, you can use session tracing - `SET TRACING=on; ... ; SET TRACING=off; SHOW TRACE FOR SESSION;` to get traces that include the planning phase and maybe that'll answer some questions about where the time is spent.
