### ISSUE TITLE
Django 2.2 causing errors in Python CockroachDB tutorial

### ISSUE THREAD

**Issue by kevinkokomani** [cockroachdb/docs#9285]
Doc: https://www.cockroachlabs.com/docs/stable/build-a-python-app-with-cockroachdb-django.html

A customer reached out reporting that they were not able to get the above tutorial working with Django 2.2, and at the top of the doc it says that 2.2 is supported. I tried to reproduce locally with my own installation of Django 2.2.17 and ran into the error below. This was on [Step 6](https://www.cockroachlabs.com/docs/stable/build-a-python-app-with-cockroachdb-django.html#step-6-set-up-and-run-the-django-app) after running `python manage.py migrate`.

```
kevinkokomani@Kevins-MacBook-Pro django_testproject % python manage.py makemigrations cockroach_example

Migrations for 'cockroach_example':
  cockroach_example/migrations/0001_initial.py
    - Create model Customers
    - Create model Products
    - Create model Orders
kevinkokomani@Kevins-MacBook-Pro django_testproject % python manage.py migrate

Operations to perform:
  Apply all migrations: admin, auth, cockroach_example, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length...Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.FeatureNotSupported: unimplemented: ALTER COLUMN TYPE from varchar to varchar is prohibited until v21.1
HINT:  You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/54844/v20.2


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kevinkokomani/django_testproject/manage.py", line 21, in <module>
    main()
  File "/Users/kevinkokomani/django_testproject/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 232, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/operations/fields.py", line 249, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 534, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type,
  File "/usr/local/lib/python3.9/site-packages/django_cockroachdb/schema.py", line 35, in _alter_field
    BaseDatabaseSchemaEditor._alter_field(
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 680, in _alter_field
    self.execute(
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.NotSupportedError: unimplemented: ALTER COLUMN TYPE from varchar to varchar is prohibited until v21.1
HINT:  You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/54844/v20.2
```

Note that https://go.crdb.dev/issue-v/54844/v20.2 does link out to an issue.

**Comment by ericharmeling** [comment]
It looks like whichever version of the cockroachdb adapter you are using isn't catching a prohibited `ALTER TABLE SET DATA TYPE` statement, but CRDB is catching it and returning an error to the client (hence the `HINT` and linked issue). 
@rafiss  Does that sound right?

It appears that https://github.com/cockroachdb/django-cockroachdb/pull/198 resolves this in the latest (albeit *untagged*) version of `django-cockroachdb` (which would theoretically be 3.1.3 I believe?). 

We might need to add a note in the docs... something to the effect of "CockroachDB versions > v20.2 do not support Django versions < 3.1.3." or something like that...

**Comment by rafiss** [comment]
The more accurate statement (which we should include in the docs) is "In order to use CockroachDB 20.2, you must use Django>=3.1 and django-cockroachdb>=3.1."

So to fully list out all the version combos that work:
* CockroachDB 19.2 works with Django 2.2 and Django 3.0
* CockroachDB 20.1 works with Django 2.2, Django 3.0, and Django 3.1
* CockroachDB 20.2 works with Django 3.1
